import bcrypt from "bcryptjs"
const data = {
  users: [
    {
      name: 'manoochehr',
      email: 'ghiyaee47@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin:true,
    },
    {
      name: 'farnoosh',
      email: 'farnoosh@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin:false,
    },
  ],
  products: [
    {
      // _id:1,
      name: 'Iphone 14',
      categoty: 'Mobile',
      image: '/images/p1.png',
      price: 2000,
      countInStock: 3,
      brand: 'appel 14',
      rating: 5.5,
      numberReviews: 10,
      descp: 'کیفیت عالی',
    },
    {
      // _id: 2,
      name: 'Iphone 13',
      categoty: 'Mobile',
      image: '/images/p2.png',
      price: 1800,
      countInStock: 4,
      brand: 'appel 13',
      rating: 2,
      numberReviews: 12,
      descp: 'کیفیت عالی',
    },
    {
      // _id: 3,
      name: 'Iphone 12',
      categoty: 'Mobile',
      image: '/images/p3.png',
      price: 1500,
      countInStock: 2,
      brand: 'appel 12',
      rating: 2.5,
      numberReviews: 7,
      descp: 'کیفیت عالی',
    },
    {
      // _id: 4,
      name: 'Iphone 11',
      categoty: 'Mobile',
      image: '/images/p4.png',
      price: 1000,
      countInStock: 0,
      brand: 'appel 11',
      rating: 5.0,
      numberReviews: 20,
      descp: 'کیفیت عالی',
    },
  ],
};
export default data
