const data = {
  products: [
    {
      name: 'Iphone 14',
      categoty: 'Mobile',
      image: '/images/p1.png',
      price: 2000,
      countInStock: 12,
      brand: 'appel',
      rating: 4.5,
      numberReview: 10,
      descp: 'hight quality',
    },
    {
      name: 'Iphone 13',
      categoty: 'Mobile',
      image: '/images/p2.png',
      price: 1800,
      countInStock: 10,
      brand: 'appel',
      rating: 4.0,
      numberReview: 12,
      descp: 'hight quality',
    },
    {
      name: 'Iphone 12',
      categoty: 'Mobile',
      image: '/images/p3.png',
      price: 1500,
      countInStock: 14,
      brand: 'appel',
      rating: 4.0,
      numberReview: 7,
      descp: 'hight quality',
    },
    {
      name: 'Iphone 11',
      categoty: 'Mobile',
      image: './images/p4.png',
      price: 1000,
      countInStock: 5,
      brand: 'appel',
      rating: 5.0,
      numberReview: 20,
      descp: 'hight quality',
    },
  ],
};
export default data
